export const materiaPorTurmas = {
            "INF-211": [
                "Artes I",
                "Biologia I",
                "Educação Física I",
                "Filosofia I",
                "Geografia I",
                "História I",
                "Língua Portuguesa e Literatura Brasileira I",
                "Matemática I",
                "Organização de Computadores",
                "Quimica Geral I",
                "Segurança, Meio Ambiente e Saúde",
                "Sociologia I",
            ],
            "INF-221": [
                "Artes II",
                "Biologia II",
                "Educação Física II",
                "Filosofia II",
                "Física I",
                "Geografia II",
                "História II",
                "Língua Portuguesa e Literatura Brasileira II",
                "Lógica Computacional",
                "Manutenção de Computadores",
                "Quimica Geral II",
                "Matemática II",
                "Sociologia II",
            ],
            "INF-231": [
                "Banco de Dados",
                "Biologia III",
                "Educação Física III",
                "Filosofia III",
                "Física II",
                "Geografia III",
                "Historia III",
                "Ingles Instrumental I",
                "Língua Portuguesa e Literatura Brasileira III",
                "Matematica III",
                "Programação I",
                "Quimica Organica",
                "Sociologia III",
            ],
            "INF-241": [
                "Biologia IV",
                "Desenvolvimento WEB I",
                "Educação física IV",
                "Filosofia IV",
                "Física III",
                "Fisico-Quimica I",
                "Geografia IV",
                "Historia IV",
                "Ingles Instrumental II",
                "Língua Portuguesa e Literatura Brasileira IV",
                "Matematica IV",
                "Programação II",
                "Redes de Computadores",
                "Sociologia IV",
            ],
            "INF-251": [
                "Biologia V",
                "Desenvolvimento WEB II",
                "Educação física V",
                "Filosofia V",
                "Física IV",
                "Fisico-Quimica II",
                "Geografia V",
                "Historia V",
                "Ingles Instrumental III",
                "Língua Portuguesa e Literatura Brasileira V",
                "Matematica V",
                "Projeto Computacional I",
                "Sistema Operacionais",
            ],
            "INF-261": [
                "Biologia VI",
                "Educação Física VI",
                "Física V",
                "História VI",
                "Ingles Instrumental IV",
                "Língua Portuguesa e Literatura Brasileira VI",
                "Matematica VI",
                "Midias, Tecnologias, ambiente e sociedade",
                "Projeto Computaional II",
                "Tecnologias Computacionais",
            ],
            "INF-OPT": [
                "Língua Espanhola I",
                "Língua Espanhola II",
                "Língua Espanhola III",
            ],}